/**
 * Google Analytics 4, delivered in-page and under the site's own Content-Security-Policy.
 *
 * Each operator's `site.analytics` names up to two kinds of measurement ID:
 *
 *   gtagId         — the site's own GA4 property. Optional: an operator without one ships the
 *                    roll-up alone.
 *   gtagRollupIds  — the cross-site roll-up stream(s) the site reports into as well.
 *
 * The layout emits exactly one gtag.js loader (the per-site ID when there is one, else the first
 * roll-up) and a same-origin bootstrap, /ga4.js, that configures every ID. The bootstrap is a file
 * rather than an inline <script> because the CSP carries no 'unsafe-inline', no nonce, and no hash
 * for scripts — an inline `gtag('config', …)` is refused, and GA4 then records nothing.
 *
 * The per-site ID lives here in the page, not in Cloudflare Zaraz: Zaraz GA4 tools on these zones
 * fire but GA4 recorded zero sessions from them, while in-page tags record normally.
 */

const MEASUREMENT_ID = /^G-[A-Z0-9]{4,20}$/

/** Every ID the site configures, per-site first, de-duplicated. Empty means no GA4 at all. */
export function ga4Ids (site) {
  const a = (site && site.analytics) || {}
  const ids = [...new Set([a.gtagId, ...(a.gtagRollupIds || [])].filter(Boolean))]
  // The IDs are written into a script file, so anything but a measurement ID is refused outright.
  for (const id of ids) {
    if (!MEASUREMENT_ID.test(id)) throw new Error(`site.analytics: "${id}" is not a GA4 measurement ID`)
  }
  return ids
}

/** The single ID the gtag.js loader is requested with, or null when the site has none. */
export function ga4LoaderId (site) {
  return ga4Ids(site)[0] || null
}

/** Contents of /ga4.js, or null when the site has no GA4 ID. */
export function ga4Bootstrap (site) {
  const ids = ga4Ids(site)
  if (!ids.length) return null
  return [
    '/* Generated by src/build.mjs from site.analytics — see src/lib/ga4.mjs. */',
    'window.dataLayer = window.dataLayer || [];',
    'function gtag() { window.dataLayer.push(arguments); }',
    'gtag("js", new Date());',
    ...ids.map((id) => `gtag("config", ${JSON.stringify(id)});`),
    '',
  ].join('\n')
}
